### ISSUE TITLE
Doubt about admin options

### ISSUE THREAD

**Issue by UO270115** [Arquisoft/radarin_en2b#68]
The Radarin description shows some kind admin options to manage users and monitor server status. I understand that the last one is regarding prometheus and grafana dashboards that you tolds us in Monday's class that is not that important for the next "delivery".

I remember that we have sometimes talked about admin options as eliminating users and locations from the app.

If I create at least one admin account that has the ability to remove users from the app, could they register / login again? Because what I understand / think now is that the admin can delete the user from the mongo database and that is all.

What about users locations? I am not very sure if the admin can have that specific kind of information and if that account can, what is the link between the different users? Are the list of available locations the database locations? If a user is removed from the database the corresponding location should be removed too?

Apart from updated the webapp api.js as I have already done, I have choose this work to do in order to try to finish as much as possible a basic version of the webapp as the requirements asked us.

**Comment by pglez82** [comment]
> The Radarin description shows some kind admin options to manage users and monitor server status. I understand that the last one is regarding prometheus and grafana dashboards that you tolds us in Monday's class that is not that important for the next "delivery".

Yes, the monitoring options can be left out for the next delivery.

> I remember that we have sometimes talked about admin options as eliminating users and locations from the app.
If I create at least one admin account that has the ability to remove users from the app, could they register / login again? Because what I understand / think now is that the admin can delete the user from the mongo database and that is all.

These decisions are up to you as the assignment is quite open. It says `The application will allow the users to manage and visualize locations and it will also include other admin options to manage users`. That means that a bare minimum would be to allow users to view and delete locations and have an admin role that would be able to delete an account from the system. With this last part, I understand that when a user starts using your application it should register in it so the server part has some information about the user that the admin will be able to delete. In my opinion the information stored in the pod should not be touched by default as the user is the owner of that info.

About the ability to log in again after a user has been deleted, that decision is up to you. Not allowing the user to register again will be something like banning an account. For me, that would be a different functionality.
