### ISSUE TITLE
3. System Scope and Context

### ISSUE THREAD

**Issue by uo269787** [Arquisoft/radarin_en2b#7]
3.1. Business Context

3.2. Technical Context

**Comment by uo269787** [comment]
This is a draft of the business context from section 3. 

We have a DB were we only store WebID, location & timestamps, and authentication tokens if needed for SOLID-OIDC.

Friends WebIDs are retrieved from the user pods and then checked against the DB to see if they are nearby, but they are never stored, so every time the application wants to check for a user's friends it needs to check the pod.

Are we understanding it correctly? Is the SOLID side correct? @pglez82 

![imagen](https://user-images.githubusercontent.com/60620685/107221860-7cc35b80-6a14-11eb-9774-fbd5204b081c.png)

**Comment by pglez82** [comment]
The diagram makes perfect sense to me and its a possible solution. The concern that you should have is if a design like this would be efficient enough to satisfy the quality attributes that you establish for the project. 

All of the team members should take a look at this diagram and a discussion should take place because it will condition your implementation later on.

Good job by the way. This diagram is a great starting point.
